
private object Versions {
    const val KOTLIN = "1.3.61"
    const val APPCOMPAT = "1.2.0"
    const val MATERIAL = "1.2.0-alpha05"
    const val COROUTINES = "1.3.3"
    const val CANARINHO = "1.2.0"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.1.0"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.2.0-alpha02"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-alpha02"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.7.0"
    const val LOGGING = "4.2.2"
    const val MOSHI = "1.9.2"
    const val COIL = "0.8.0"
    const val ZXING = "3.3.3"
    const val ZXING_EMBEDDED = "4.1.0"
    const val KOIN = "2.0.1"
    const val PAGE_INDICATOR = "1.0.0@aar"
    const val PLAY_CORE = "1.8.0"
    const val HAWK = "2.0.1"
    const val ROOM = "2.2.3"
    const val SHIMER = "0.5.0"
    const val GLIDE = "4.9.0"
    const val GOOGLE_SERVICES = "17.0.0"
    const val EXPANSIONPANEL = "1.2.2"
    const val THREETENBP = "1.4.4"
    const val WORK_RUNTIME = "2.3.3"
    const val NAV_VERSION = "2.3.0"
    const val LEGACY_SUPPORT = "1.0.0"

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val MOCKK = "1.9.3"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.0-alpha02"
    const val MOCK_WEB_SERVER = "4.2.2"
    const val HAMCREST = "1.3"
}

object Dependencies {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.KOTLIN}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${Versions.APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${Versions.MATERIAL}"

    const val RECYCLE_VIEW = "androidx.recyclerview:recyclerview:${Versions.RECYCLE_VIEW}"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT_LAYOUT}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.SWIPE_REFRESH_LAYOUT}"

    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINES}"
    const val COROUTINES_PLAY_SERVICE = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.COROUTINES}"

    const val CORE_KTX = "androidx.core:core-ktx:${Versions.CORE_KTX}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${Versions.FRAGMENT_KTX}"

    const val LIFECYCLE_EXTENSIONS = "androidx.lifecycle:lifecycle-extensions:${Versions.LIFECYCLE}"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.LIFECYCLE}"

    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-gson:${Versions.RETROFIT}"
    const val LOGGING = "com.squareup.okhttp3:logging-interceptor:${Versions.LOGGING}"
    const val TIMBER = "com.jakewharton.timber:timber:${Versions.TIMBER}"
    const val MOSHI = "com.squareup.moshi:moshi:${Versions.MOSHI}"
    const val MOSHI_KTX = "com.squareup.moshi:moshi-kotlin:${Versions.MOSHI}"
    const val MOSHI_ADAPTERS = "com.squareup.moshi:moshi-adapters:${Versions.MOSHI}"
    const val COIL = "io.coil-kt:coil:${Versions.COIL}"
    const val ZXING = "com.google.zxing:core:${Versions.ZXING}"
    const val ZXING_EMBEDDED = "com.journeyapps:zxing-android-embedded:${Versions.ZXING_EMBEDDED}"
    const val KOIN = "org.koin:koin-android:${Versions.KOIN}"
    const val KOIN_SCOPE = "org.koin:koin-android-scope:${Versions.KOIN}"
    const val KOIN_VIEWMODEL = "org.koin:koin-android-viewmodel:${Versions.KOIN}"
    const val PAGE_INDICATOR = "com.romandanylyk:pageindicatorview:${Versions.PAGE_INDICATOR}"
    const val PLAY_CORE = "com.google.android.play:core:${Versions.PLAY_CORE}"
    const val PLAY_CORE_KTX = "com.google.android.play:core-ktx:${Versions.PLAY_CORE}"
    const val HAWK = "com.orhanobut:hawk:${Versions.HAWK}"
    const val ROOM = "androidx.room:room-runtime:${Versions.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${Versions.ROOM}"
    const val WORK_RUNTIME = "androidx.work:work-runtime:${Versions.WORK_RUNTIME}"
    const val SHIMER = "com.facebook.shimmer:shimmer:${Versions.SHIMER}"
    const val RETROFIT_CONVERTER_MOSHI = "com.squareup.retrofit2:converter-moshi:${Versions.RETROFIT}"
    const val GLIDE = "com.github.bumptech.glide:glide:${Versions.GLIDE}"
    const val JOTLIN_STDLLIB = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.KOTLIN}"
    const val EXPANSIONPANEL = "com.github.florent37:expansionpanel:${Versions.EXPANSIONPANEL}"
    const val GOOGLE_ANALYTICS = "com.google.android.gms:play-services-analytics:${Versions.GOOGLE_SERVICES}"
    const val GOOGLE_ANALYTICS_TAG_MANAGER = "com.google.android.gms:play-services-tagmanager:${Versions.GOOGLE_SERVICES}"
    const val GOOGLE_SERVICES = "com.google.android.gms:play-services-base:${Versions.GOOGLE_SERVICES}"
    const val THREETENBP = "org.threeten:threetenbp:${Versions.THREETENBP}"

    const val SERVICES_LOCATION = "com.google.android.gms:play-services-location:${Versions.GOOGLE_SERVICES}"
    const val GUAVA = "com.google.guava:guava:27.0.1-android"
    const val LEGACY_SUPPORT = "androidx.legacy:legacy-support-v4:${Versions.LEGACY_SUPPORT}"

    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment:${Versions.NAV_VERSION}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui:${Versions.NAV_VERSION}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${Versions.NAV_VERSION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${Versions.NAV_VERSION}"
    const val NAVIGATION_DF_FRAGMENT = "androidx.navigation:navigation-dynamic-features-fragment:${Versions.NAV_VERSION}"
}

object TestDependencies {
    const val JUNIT = "junit:junit:${Versions.JUNIT}"
    const val MOCKK = "io.mockk:mockk:${Versions.MOCKK}"
    const val EXT = "androidx.test.ext:junit:${Versions.EXT}"
    const val CORE = "androidx.test:core:${Versions.TEST}"
    const val RUNNER = "androidx.test:runner:${Versions.TEST}"
    const val RULES = "androidx.test:rules:${Versions.TEST}"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.COROUTINES}"
    const val ARCH_CORE = "androidx.arch.core:core-testing:${Versions.ARCH_CORE}"
    const val FRAGMENT_TEST = "androidx.fragment:fragment-testing:${Versions.FRAGMENT_TEST}"
    const val MOCK_WEB_SERVER = "com.squareup.okhttp3:mockwebserver:${Versions.MOCK_WEB_SERVER}"
    const val HAMCREST = "org.hamcrest:hamcrest-all:${Versions.HAMCREST}"
    const val NAVIGATION_TESTING = "androidx.navigation:navigation-testing:${Versions.NAV_VERSION}"

}

object DebugDependencies {
    const val LEAKCANARY = "com.squareup.leakcanary:leakcanary-android:2.0"
}

